# Generated by Django 4.2.2 on 2023-09-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
