# Generated by Django 4.2.2 on 2023-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_remove_comment_author_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
